# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testrunner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='localhost', max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Test',
            new_name='TestModule',
        ),
        migrations.AlterField(
            model_name='testrun',
            name='last_result',
            field=models.CharField(choices=[('pass', 'pass'), ('fail', 'fail'), ('error', 'error'), ('never_run', 'never_run')], default='never_run', max_length=20),
        ),
        migrations.AlterField(
            model_name='testruninstance',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testrunner.TestEnvironment'),
        ),
        migrations.DeleteModel(
            name='Environment',
        ),
    ]
