# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 23:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testrunner', '0003_auto_20170808_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
