# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testrunner', '0004_auto_20170808_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='last_result',
            field=models.CharField(choices=[('pass', 'pass'), ('fail', 'fail'), ('error', 'error')], max_length=20, null=True),
        ),
    ]
