# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 01:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testrunner', '0005_auto_20170809_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
