# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 00:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testrunner', '0008_auto_20170809_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='label',
            field=models.CharField(default='unnamed', max_length=40, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='modules',
            field=models.ManyToManyField(to='testrunner.TestModule'),
        ),
        migrations.AddField(
            model_name='testmodule',
            name='path',
            field=models.CharField(default='.', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testmodule',
            name='result',
            field=models.CharField(choices=[('pass', 'pass'), ('fail', 'fail'), ('error', 'error')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='testrun',
            name='modules',
            field=models.ManyToManyField(to='testrunner.TestModule'),
        ),
        migrations.AddField(
            model_name='testruninstance',
            name='output',
            field=models.CharField(default='no output', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testruninstance',
            name='result',
            field=models.CharField(choices=[('pass', 'pass'), ('fail', 'fail'), ('error', 'error')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='testruninstance',
            name='testrun',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testrunner.TestRun'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testruninstance',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
