# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testrunner', '0013_auto_20170812_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='testruninstance',
            name='status',
            field=models.CharField(choices=[('stopped', 'stopped'), ('running', 'running')], default='stopped', max_length=20),
        ),
    ]
