# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testrunner', '0014_testruninstance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodule',
            name='result',
            field=models.CharField(choices=[('PASSED', 'PASSED'), ('FAILED', 'FAILED'), ('ERROR', 'ERROR')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='last_result',
            field=models.CharField(choices=[('PASSED', 'PASSED'), ('FAILED', 'FAILED'), ('ERROR', 'ERROR')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='testruninstance',
            name='result',
            field=models.CharField(choices=[('PASSED', 'PASSED'), ('FAILED', 'FAILED'), ('ERROR', 'ERROR')], max_length=20, null=True),
        ),
    ]
