# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testrunner', '0015_auto_20170812_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testruninstance',
            name='output',
            field=models.CharField(max_length=65000, null=True),
        ),
    ]
