# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testrunner', '0016_auto_20170812_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='testenvironment',
            name='state',
            field=models.CharField(default='idle', max_length=20),
        ),
    ]
