# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testrunner', '0017_testenvironment_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testenvironment',
            name='state',
            field=models.CharField(choices=[('idle', 'idle'), ('inuse', 'inuse')], default='idle', max_length=20),
        ),
    ]
