# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testrunner', '0018_auto_20170812_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testmodule',
            old_name='result',
            new_name='last_result',
        ),
        migrations.AlterField(
            model_name='testmodule',
            name='path',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
